version: "3"

tasks:
  generate:
    aliases:
      - gen
    description: "Generate protobuf code"
    cmds:
      - protoc -I ./proto-files ./proto-files/status/status.proto --go_out=./pkg --go_opt=paths=source_relative --go-grpc_out=./pkg --go-grpc_opt=paths=source_relative
      - protoc -I ./proto-files ./proto-files/task/task.proto --go_out=./pkg --go_opt=paths=source_relative --go-grpc_out=./pkg --go-grpc_opt=paths=source_relative
      - protoc -I ./proto-files ./proto-files/user/user.proto --go_out=./pkg --go_opt=paths=source_relative --go-grpc_out=./pkg --go-grpc_opt=paths=source_relative